# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

default-job: &default-job
  working_directory: /tmp/natserract
  docker:
    - image: cimg/node:18.20

commands:
  install_packages:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable --install-directory ~/bin
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: View install environment
          command: |
            node --version
            pnpm --version
      - run:
          name: Install Dependencies
          command: |
            pnpm install

jobs:
  checkout:
    <<: *default-job
    steps:
      - checkout
      - install_packages

  test_lint:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Lint
          command: pnpm lint
  test_static:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Prettier check
          command: pnpm prettier --check
  test_types:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Tests TypeScript definitions
          command: pnpm typescript
          environment:
            NODE_OPTIONS: --max-old-space-size=3072
  test_builds:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Prepare danger on PRs
          command: pnpm danger ci
          environment:
            DANGER_COMMAND: checkGitCommitMessage
  test_regressions:
    <<: *default-job
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.1-focal
        environment:
          NODE_ENV: development # Needed if playwright is in `devDependencies`
    steps:
      - checkout
      - install_packages
      - run:
          name: Upload screenshots to Argos CI
          command: pnpm test:argos
          environment:
            CI: "true"

workflows:
  version: 2
  react-next:
    jobs:
      - checkout
      - test_lint
      - test_static:
          requires:
            - checkout
      - test_types:
          requires:
            - checkout
      - test_builds:
          requires:
            - checkout
      - test_regressions:
          requires:
            - checkout
