# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

default-job: &default-job
  docker:
    - image: cimg/node:lts

commands:
  install_packages:
    steps:
      - run:
          name: Install pnpm
          command: npm i -g pnpm@8.15.8
          environment:
            # CircleCI uses interactive terminals (TTY) that crash Turborepo's terminal UI.
            TURBO_UI: "false"
      # look for existing cache and restore if found
      - restore_cache:
          key: npm-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install js dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: npm-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Install Vercel CLI
          command: pnpm install --global vercel@latest

jobs:
  checkout:
    <<: *default-job
    steps:
      - checkout
      - install_js

  test_lint:
    <<: *default-job
    steps:
      - checkout
      - run:
          name: Prettier
          command: pnpm lint

workflows:
  version: 2
  react-next:
    jobs:
      - test_lint
