# See: https://circleci.com/docs/configuration-reference
version: 2.1

default-job: &default-job
  working_directory: /tmp/natserract
  docker:
    - image: cimg/node:18.20

commands:
  install_packages:
    steps:
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable --install-directory ~/bin
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: View install environment
          command: |
            node --version
            pnpm --version
      - run:
          name: Install Dependencies
          command: |
            pnpm install

jobs:
  checkout:
    <<: *default-job
    steps:
      - checkout
      - install_packages

  test_lint:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Lint
          command: pnpm lint
  test_static:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Prettier check
          command: pnpm prettier --check
  test_types:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Tests TypeScript definitions
          command: pnpm typescript
          environment:
            NODE_OPTIONS: --max-old-space-size=3072
  test_builds:
    <<: *default-job
    parallelism: 6
    steps:
      - checkout
      - install_packages
      - run:
          name: Builds
          command: pnpm build
  test_regressions:
    <<: *default-job
    steps:
      - checkout
      - install_packages
      - run:
          name: Install playwright browsers
          command: npx playwright install --with-deps chromium
      - run:
          name: Prepare playwright hash
          command: pnpm list --json --filter playwright > /tmp/playwright_info.json
      - store_artifacts:
          name: Debug playwright hash
          path: /tmp/playwright_info.json
      - restore_cache:
          name: Restore playwright cache
          keys:
            - v6-playwright-{{ arch }}-{{ checksum "/tmp/playwright_info.json" }}
      - run:
          name: Run test
          command: pnpm test:regressions --project=chromium
      - save_cache:
          name: Save playwright cache
          key: v6-playwright-{{ arch }}-{{ checksum "/tmp/playwright_info.json" }}
          paths:
            # Keep path in sync with "PLAYWRIGHT_BROWSERS_PATH"
            # Can't use environment variables for `save_cache` paths (tested in https://app.circleci.com/pipelines/github/mui/material-ui/37813/workflows/5b1e207f-ac8b-44e7-9ba4-d0f9a01f5c55/jobs/223370)
            - /tmp/pw-browsers

      - run:
          name: Upload screenshots to Argos CI
          command: pnpm test:argos
          environment:
            ARGOS_TOKEN: $ARGOS_TOKEN

workflows:
  version: 2
  react-next:
    jobs:
      - checkout
      - test_lint
      - test_static:
          requires:
            - checkout
      - test_types:
          requires:
            - checkout
      - test_builds:
          requires:
            - checkout
      - test_regressions:
          requires:
            - checkout
