name: ci

on:
  pull_request_target:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    # l10nbot does not affect dev scripts.
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/pnpm-install

      - name: Danger
        run: pnpm danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

  type-check:
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Typescript Check
        run: pnpm typescript
        env:
          NODE_OPTIONS: --max-old-space-size=4096

  lint:
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      - uses: actions/checkout@v4
      - name: Prettier check
        run: pnpm prettier --check

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: pnpm lint

  e2e:
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: pnpm test:e2e

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.shard }}_${{ strategy.job-total }}
          path: test-results

      - name: Upload screenshots to Argos CI
        shell: bash
        run: pnpm test:argos
        env:
          ARGOS_TOKEN: ${{ inputs.argos-token }}

  build:
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      - uses: actions/checkout@v4

      - run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

  required:
    needs: [changes, lint, type-check, e2e, build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
