name: CI

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main
      - develop

permissions: {}

jobs:
  build:
    # l10nbot does not affect dev scripts.
    if: ${{ github.actor != 'l10nbot' }}
    strategy:
      matrix:
        # IF include all -> os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Install packages
        uses: ./.github/actions/pnpm-install

      - run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Tests TypeScript definitions
        run: pnpm typescript
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Prettier check
        run: pnpm prettier --check

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: pnpm lint

      - name: Danger
        run: pnpm danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

      - name: Test browser
        uses: ./.github/actions/run-browser
        with:
          argos-token: ${{ secrets.ARGOS_TOKEN }}
