name: code checks (sonarcloud)

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main
      - develop

  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        with:
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=natserract_frontend-automation
            -Dsonar.organization=natserract
