name: code checks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/playwright-install

      - name: Run e2e test
        run: pnpm test
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.shard }}_${{ strategy.job-total }}
          path: test-results

      - name: Upload screenshots to Argos CI
        shell: bash
        run: pnpm test:argos
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - name: Run unit test
        run: pnpm test:unit

  required:
    if: always()
    needs: [e2e, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
