name: code checks (sonarcloud)

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main
      - develop

  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
