name: release changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main # Always checkout main even for tagged releases
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/pnpm-install

      - name: Create Tags
        run: pnpm changeset tag
      - name: Tag debug
        run: git tag
      - name: Push tags
        run: git push --follow-tags

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

  output_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ release.outputs.changes }}
