name: e2e Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions: {}

jobs:
  testing:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Install packages
        uses: ./.github/actions/pnpm-install

      - name: Cypress intall tests
        id: cypress-install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          path: '~./cache/Cypress'

      - if: ${{ steps.cypress-install.outputs.cache-hit == 'true' }}
        name: Run e2e tests
        run: pnpm test
