name: e2e Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions: {}

jobs:
  testing:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Set up Cypress binary cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install packages
        uses: ./.github/actions/pnpm-install
        with:
          pnpm-frozen: 'true'

      - name: Cypress install
        id: cypress-install
        uses: cypress-io/github-action@v6
        with:
          install: false

      - name: Run e2e tests
        run: pnpm test
