name: e2e Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions: {}

jobs:
  testing:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install packages
        uses: ./.github/actions/pnpm-install
        with:
          pnpm-frozen: 'true'

      - name: Run e2e test
        run: pnpm test
