name: e2e Tests

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main
      - develop

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Install packages
        uses: ./.github/actions/pnpm-install

      - name: E2E Test (Headless)
        run: pnpm test
