name: e2e Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # There is currently a bug on chrome 100 that adds an extra space in the editor
    # container: cypress/browsers:node14.17.6-chrome100-ff98
    # container: cypress/browsers:node14.17.0-chrome88-ff89
    container: cypress/browsers:node16.5.0-chrome94-ff93
    name: E2E on Tests
    strategy:
      matrix:
        browser: ['chrome']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          browser: ${{ matrix.browser }}
          env: NEXT_PUBLIC_USE_LOCAL_CLIENT=1
          command: pnpm test:cy
          wait-on: 'http://localhost:3000'
          # wait for 3 minutes for the server to respond
          wait-on-timeout: 180
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
